#---- Installation of packages in mango/external_packages (to be moved to separate module)

#---- HOPSPACK
IF (EXISTS ${MANGO_SOURCE_DIR}/external_packages/hopspack/hopspack-2.0.2-src)
  MESSAGE ("hopspack directory already exists. Checking for required files...")
  IF (EXISTS ${MANGO_SOURCE_DIR}/external_packages/hopspack/hopspack-2.0.2-src/src/src-main)
    # not sure how to best specify that hopspack has been installed yet
    MESSAGE ("hopspack is already installed on this system")
    FILE (APPEND ${MANGO_SOURCE_DIR}/examples/packages_available "hopspack ")
  ELSE ()
    MESSAGE (FATAL_ERROR "Unsuccessful HOPSPACK Installation. Exiting...")
  ENDIF ()
ELSE ()
  EXECUTE_PROCESS (COMMAND ${MANGO_SOURCE_DIR}/external_packages/install_hopspack.sh WORKING_DIRECTORY ${MANGO_SOURCE_DIR}/external_packages RESULT_VARIABLE ierr)
  MESSAGE ("ierr hops --> ${ierr}")
  IF (${ierr})
    MESSAGE (FATAL_ERROR "Unsuccessful HOPSPACK Installation. Exiting...")
  ELSE ()
    SET (COMPILE_DEF_LIST ${COMPILE_DEF_LIST};MANGO_HOPSPACK_AVAILABLE)
  ENDIF ()
ENDIF ()
  
#---- nlopt
IF (EXISTS ${MANGO_SOURCE_DIR}/external_packages/nlopt)
   MESSAGE ("nlopt directory already exists. Checking for required files...")
   IF (EXISTS ${MANGO_SOURCE_DIR}/external_packages/nlopt/nlopt-2.6.1/install/lib64/libnlopt.a)
      MESSAGE ("nlopt is already installed on this system")
      FILE (APPEND ${MANGO_SOURCE_DIR}/examples/packages_available "nlopt ")
    ELSE ()
      MESSAGE ("nlopt was not correctly installed. Continuing without...")
    ENDIF ()
ELSE ()
   EXECUTE_PROCESS (COMMAND ${MANGO_SOURCE_DIR}/external_packages/install_nlopt.sh WORKING_DIRECTORY ${MANGO_SOURCE_DIR}/external_packages RESULT_VARIABLE ierr)
   MESSAGE ("ierr nlopt --> ${ierr}")
   IF (${ierr})
      MESSAGE ("Unsuccessful NLOPT Installation. Continuing without NLOPT")
   ELSE ()
      SET (COMPILE_DEF_LIST ${COMPILE_DEF_LIST};MANGO_NLOPT_AVAILABLE)
   ENDIF ()
ENDIF ()

#---- Catch2
IF (EXISTS ${MANGO_SOURCE_DIR}/external_packages/catch2)
   MESSAGE ("catch2 directory already exists. Checking for required files...")
   IF (EXISTS ${MANGO_SOURCE_DIR}/external_packages/catch2/catch.hpp)
      MESSAGE ("catch2 is already installed on this system")
   ELSE ()
      MESSAGE (FATAL_ERROR "catch2 was not correctly installed. Exiting...")
   ENDIF ()
ELSE ()
   EXECUTE_PROCESS (COMMAND ${MANGO_SOURCE_DIR}/external_packages/install_catch2.sh WORKING_DIRECTORY ${MANGO_SOURCE_DIR}/external_packages)
   IF (${ierr})
      MESSAGE (FATAL_ERROR "Unsuccessful Catch2 Installation. Exiting...")
   ENDIF ()
ENDIF ()

FOREACH (i IN LISTS COMPILE_DEF_LIST)
	MESSAGE ("list output --> ${i}")
ENDFOREACH ()
