# -*- mode: makefile -*-

# Dependencies:
obj/mango.o: obj/mango_problem.o
obj/mango_read_namelist.o: obj/mango_problem.o
obj/mango_optimize.o: obj/mango_problem.o
obj/mango_optimize_petsc.o: obj/mango_problem.o
obj/mango_optimize_hopspack.o: obj/mango_problem.o
obj/mango_optimize_nlopt.o: obj/mango_problem.o
