// Copyright 2019, University of Maryland and the MANGO development team.
//
// This file is part of MANGO.
//
// MANGO is free software: you can redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// MANGO is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with MANGO.  If not, see
// <https://www.gnu.org/licenses/>.

#ifndef MANGO_PACKAGE_MANGO_H
#define MANGO_PACKAGE_MANGO_H

#include "Package.hpp"

namespace mango {

  class Solver;
  class Least_squares_solver;

  class Package_mango : public Package {
  private:
    //static double nlopt_objective_function(unsigned, const double*, double*, void*); 
    // // <algorithms>
    // // This section was automatically generated by ./update_algorithms
    // void levenberg_marquardt(Least_squares_solver *);
    // void imfil(Solver *);
    // // </algorithms>

  public:
    void optimize(Solver*);
    void optimize_least_squares(Least_squares_solver*);
  };

  class Algorithm {
  public:
    virtual void solve() = 0;
  };

  class LeastSquaresAlgorithm {
  public:
    virtual void solve() = 0;
  };
}

#endif
