#ifndef MANGO_PROBLEM_DATA_H
#define MANGO_PROBLEM_DATA_H

#include <mpi.h>
#include <string>
#include <fstream>
#include <ctime>
#include "mango.hpp"

namespace mango {

  class Problem_data {
    // This class contains the ugly implementation details of the interface for Problem specified in mango.hpp.

    // Everything in this class is public because this information must be used by the concrete Package.
  public:
    algorithm_type algorithm;
    int N_parameters;
    objective_function_type objective_function;
    int function_evaluations;
    std::ofstream output_file;
    int argc;
    char** argv;
    int max_function_and_gradient_evaluations;
    bool at_least_one_success;
    double* best_state_vector;
    double best_objective_function;
    int best_function_evaluation;
    bool bound_constraints_set;
    double* lower_bounds;
    double* upper_bounds;
    clock_t start_time, best_time;
    Package* package;
    double* state_vector;
    bool centered_differences;
    double finite_difference_step_size;
    std::string output_filename;
    int max_function_evaluations;
    MPI_Partition mpi_partition;
    int verbose;
    void* user_data;

    Problem_data(int)
    ~Problem_data();

    double optimize();
    void group_leaders_loop();
    void group_leaders_least_squares_loop();
    void load_algorithm_properties();
    void set_package();
    // <optimize_packages>
    // This section was automatically generated by ./update_algorithms
    void optimize_hopspack();
    void optimize_gsl();
    void optimize_least_squares_gsl();
    // </optimize_packages>
    void write_function_evaluation_and_time(clock_t);
    void compose_x_f_string(std::string&, const double*, double);
    void compose_residuals_string(std::string&, double*);
    void write_file_line(clock_t, const double*, double);
    double residuals_to_single_objective(double*);
    void write_least_squares_file_line(clock_t, const double*, double, double*);
#ifdef MANGO_GSL_AVAILABLE
    static int gsl_residual_function(const gsl_vector*, void*, gsl_vector*);
    static int gsl_residual_function_and_Jacobian(const gsl_vector*, void*, gsl_matrix*);
    static double gsl_objective_function(const gsl_vector*, void*);
    static void gsl_gradient(const gsl_vector*, void*, gsl_vector*);
    static void gsl_objective_function_and_gradient(const gsl_vector*, void*, double*, gsl_vector*);
#endif
    void objective_function_wrapper(const double*, double*, bool*); 
    void residual_function_wrapper(const double*, double*, bool*); 
    static void least_squares_to_single_objective(int*, const double*, double*, int*, mango::problem*, void*);
    void finite_difference_gradient(const double*, double*, double*);
    void finite_difference_Jacobian(const double*, double*, double*);
    void finite_difference_Jacobian_to_gradient(const double*, double*, double*);
    void write_hopspack_line_to_file(std::string line, double);
  };

}

#endif
