// Copyright 2019, University of Maryland and the MANGO development team.
//
// This file is part of MANGO.
//
// MANGO is free software: you can redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// MANGO is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with MANGO.  If not, see
// <https://www.gnu.org/licenses/>.

#include <stdexcept>
#include "mango.hpp"
#include "Solver.hpp"
// <includes>
    // This section was automatically generated by ./update_algorithms
#include "Package_petsc.hpp"
#include "Package_mango.hpp"
#include "Package_gsl.hpp"
#include "Package_hopspack.hpp"
#include "Package_nlopt.hpp"
// </includes>

// This file is the only place where the core of mango (specifically Solver) knows
// anything about the concrete Packages available.

void mango::Solver::set_package() {
  switch (algorithms[algorithm].package) {
    // <packages>
    // This section was automatically generated by ./update_algorithms
  case PACKAGE_PETSC:
    package = new Package_petsc();
    break;
  case PACKAGE_MANGO:
    package = new Package_mango();
    break;
  case PACKAGE_GSL:
    package = new Package_gsl();
    break;
  case PACKAGE_HOPSPACK:
    package = new Package_hopspack();
    break;
  case PACKAGE_NLOPT:
    package = new Package_nlopt();
    break;
    // </packages>
  default:
    throw std::runtime_error("Unknown package in mango::Solver::set_package");
  }
}
