#include <stdexcept>
#include "mango.hpp"
#include "Solver.hpp"
// <includes>
    // This section was automatically generated by ./update_algorithms
#include "Package_hopspack.hpp"
#include "Package_nlopt.hpp"
#include "Package_gsl.hpp"
#include "Package_petsc.hpp"
// </includes>

// This file is the only place where the core of mango (specifically Solver) knows
// anything about the concrete Packages available.

void mango::Solver::set_package() {
  switch (algorithms[algorithm].package) {
    // <packages>
    // This section was automatically generated by ./update_algorithms
  case PACKAGE_HOPSPACK:
    package = new Package_hopspack();
    break;
  case PACKAGE_NLOPT:
    package = new Package_nlopt();
    break;
  case PACKAGE_GSL:
    package = new Package_gsl();
    break;
  case PACKAGE_PETSC:
    package = new Package_petsc();
    break;
    // </packages>
  default:
    throw std::runtime_error("Unknown package in mango::Solver::set_package");
  }
}
