#!/usr/bin/env python

# <nondeterministic_algorithms>
## This section was automatically generated by ./update_algorithms
nondeterministic_algorithms = ["petsc_pounders","nlopt_gn_direct_l_rand","nlopt_gn_direct_l_rand_noscal","nlopt_gn_crs2_lm","nlopt_ln_praxis"]
# </nondeterministic_algorithms>

#'petsc_pounders','nlopt_gn_direct_l_rand','nlopt_gn_direct_l_rand_noscal','nlopt_gn_crs2_lm','nlopt_ln_praxis']
