name: Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Doxygen
      run: sudo apt-get doxygen doxygen-latex doxygen-doc
    - name: Generate docs
      working-directory: ./docs
      run: /usr/bin/doxygen
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        force_orphan: true
